/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.senac.view.home;

import com.senac.helpers.layouts.CentralizePanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author caetano.8918
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
//        GridBagConstraints gbc = new GridBagConstraints();
//        
//        gbc.gridx = 0;
//        gbc.gridy = 0;
//        gbc.weightx = 1.0;
//        gbc.weighty = 1.0;
//        gbc.fill = GridBagConstraints.CENTER;
        
        CentralizePanel.centralize(jPanel1, jpButtons);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jpButtons = new javax.swing.JPanel();
        btnAddPedidos = new javax.swing.JButton();
        btnVerPedidos = new javax.swing.JButton();
        btnCardapio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadProd = new javax.swing.JMenuItem();
        miCadCategoria = new javax.swing.JMenuItem();
        miCadProducao = new javax.swing.JMenuItem();
        miCadRestricao = new javax.swing.JMenuItem();
        miFazerPedido = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miVisuPedido = new javax.swing.JMenuItem();
        miVisuCardapio = new javax.swing.JMenuItem();
        miVisuCategoria = new javax.swing.JMenuItem();
        miVisuRestricao = new javax.swing.JMenuItem();
        miVisuProducao = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddPedidos.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        btnAddPedidos.setText("Adicionar Pedidos");
        btnAddPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPedidosActionPerformed(evt);
            }
        });

        btnVerPedidos.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        btnVerPedidos.setText("Ver Pedidos");
        btnVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPedidosActionPerformed(evt);
            }
        });

        btnCardapio.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        btnCardapio.setText("Cardápio");
        btnCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardapioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonsLayout = new javax.swing.GroupLayout(jpButtons);
        jpButtons.setLayout(jpButtonsLayout);
        jpButtonsLayout.setHorizontalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpButtonsLayout.setVerticalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro");

        miCadProd.setText("Cadastrar Produto");
        miCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadProdActionPerformed(evt);
            }
        });
        jMenu1.add(miCadProd);

        miCadCategoria.setText("Cadastrar Categoria");
        miCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadCategoria);

        miCadProducao.setText("Cadastrar Produção");
        miCadProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadProducaoActionPerformed(evt);
            }
        });
        jMenu1.add(miCadProducao);

        miCadRestricao.setText("Cadastrar Restrição");
        jMenu1.add(miCadRestricao);

        miFazerPedido.setText("Fazer Pedido");
        jMenu1.add(miFazerPedido);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Visualizar");

        miVisuPedido.setText("Pedidos");
        jMenu2.add(miVisuPedido);

        miVisuCardapio.setText("Cardapio");
        miVisuCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisuCardapioActionPerformed(evt);
            }
        });
        jMenu2.add(miVisuCardapio);

        miVisuCategoria.setText("Categoria");
        jMenu2.add(miVisuCategoria);

        miVisuRestricao.setText("Restrições");
        jMenu2.add(miVisuRestricao);

        miVisuProducao.setText("Produção");
        jMenu2.add(miVisuProducao);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerPedidosActionPerformed

    private void miCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadProdActionPerformed

    private void btnAddPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPedidosActionPerformed

    private void miCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadCategoriaActionPerformed

    private void miCadProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadProducaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadProducaoActionPerformed

    private void btnCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardapioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCardapioActionPerformed

    private void miVisuCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisuCardapioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miVisuCardapioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPedidos;
    private javax.swing.JButton btnCardapio;
    private javax.swing.JButton btnVerPedidos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JMenuItem miCadCategoria;
    private javax.swing.JMenuItem miCadProd;
    private javax.swing.JMenuItem miCadProducao;
    private javax.swing.JMenuItem miCadRestricao;
    private javax.swing.JMenuItem miFazerPedido;
    private javax.swing.JMenuItem miVisuCardapio;
    private javax.swing.JMenuItem miVisuCategoria;
    private javax.swing.JMenuItem miVisuPedido;
    private javax.swing.JMenuItem miVisuProducao;
    private javax.swing.JMenuItem miVisuRestricao;
    // End of variables declaration//GEN-END:variables
}
